name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run integration tests
        run: dotnet test tests/Api.IntegrationTests/Api.IntegrationTests.csproj --no-build -c Release --logger "github"

      - name: Install Playwright browsers
        run: pwsh tests/Playwright.Tests/bin/Release/net10.0/playwright.ps1 install --with-deps chromium

      - name: Run Playwright tests
        run: dotnet test tests/Playwright.Tests/Playwright.Tests.csproj --no-build -c Release --logger "github"
        env:
          BROWSER: chromium